### ISSUE TITLE
Standaryzacja zmiennych - testthat

### ISSUE THREAD

**Issue by kozaka93** [kozaka93/toRpEDA#128]
Dwa testy dla normalizacji nie przechodzą. Możliwe, że po zmianie kodu nie działa jak powinno.

![obraz](https://github.com/kozaka93/toRpEDA/assets/24189252/adfe53a2-94ad-4c60-b398-4bace0253eec)

**Comment by klopotowskik** [comment]
zmergowałem poprawkę, testy przechodzą.
